### ISSUE TITLE
It doesn't work as expected

### ISSUE THREAD

**Issue by Yassdrk** [47ng/session-keystore#330]
Hi,

I was trying the package but it doesn't work as expected. 

How can i call the session storage in another page ? I mean, i created the session storage in the login page to save the private key, but i want to call it in the dashboard page.

**Comment by franky47** [comment]
Hi, it depends on your setup, the `SessionKeystore` instance keeps its secrets in memory, so as long as it's available on both pages, you should be able to access it.

You should probably define it in another file, and access it from both pages:

```ts
// keystore.ts
import { SessionKeystore } from 'session-keystore'

export const keystore = new SessionKeystore()
```

```ts
// login.ts
import { keystore } from './keystore'

function login() {
  keystore.set('key', 'supersecret')
}
```

```ts
// dashboard.ts
import { keystore } from './keystore'

function doSomethingWithTheKey() {
  const key = keystore.get('key')
  // ...
}
```

**Comment by franky47** [comment]
Note: `session-keystore` does not work across tabs or windows, if that's a use-case you need, you can look into [`local-state-sync`](https://www.npmjs.com/package/local-state-sync) that I just (pre)published.
